[tool.poetry]
name = "neo4j_runway"
version = "0.2.1"
description = "A Python library that contains tools for data discovery, data model generation and ingestion for the Neo4j graph database."
authors = ["Alex Gilmore", "Jason Booth", "Dan Bukowski"]
license = "MIT"
readme = "README.md"

exclude = [
    "neo4j_runway/main/data/",
    "neo4j_runway/main/test_downloads/",
    "neo4j_runway/main/test_output/",
    "neo4j_runway/main/tests/"

]

[tool.poetry.dependencies]
python = "^3.12"
graphviz = "^0.20.1"
instructor = "^0.5.2"
neo4j = "^5.19.0"
openai = "^1.12.0"
pandas = "^2.0.3"
pydantic = "^2.6.1"
pyyaml = "^6.0.1"
jmespath = "^0.10.0"
numpy = "^1.26.3"
python-dateutil = "^2.8.2"
pytz = "^2023.4"
regex= "^2022.10.31"
smart-open = "^7.0.1"
urllib3 = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
